name: Deploy & Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  deploy_release:
    name: Deploy & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Test code
        run: npm test

      - name: Build code
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Release to GitHub Packages
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
        run: npm run release

      - name: Clean up compiled files
        run: npm run clean

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
        run: npx cdk deploy --require-approval never
