name: Upgrade CDK dependencies

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Testing
        run: npm test

      - name: Upgrade CDK
        run: |
          npm i --save \
            aws-cdk@latest \
            aws-cdk-lib@latest \
            constructs@latest

      - name: Re-Testing
        run: npm test

      - name: Configuring git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Adding files to git
        run: git add .

      - name: Configure git, commit and push
        run: |
          git commit -m "perf: :arrow_up: Upgraded aws-cdk-lib@`npm ls aws-cdk-lib |  grep aws-cdk-lib | sed '/deduped$/d' | cut -d '@' -f 2`" || echo 'Do nothing'
          git push
